### ISSUE TITLE
TypeError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]

### ISSUE THREAD

**Issue by junwei-h** [wbsg-uni-mannheim/contrastive-product-matching#4]
Hello,
Try to run
```python
bash abtbuy/run_pretraining_clean_roberta.sh 1024 5e-5 0.07 all
```
on Ubuntu with GPU, torch==1.13.1, but got the following error. I was not able to catch the None as suggested by [here](https://stackoverflow.com/questions/63517293/valueerror-textencodeinput-must-be-uniontextinputsequence-tupleinputsequence). The data were prepared using 
*src/processing/preprocess/preprocess_deepmatcher_datasets.py*
*src/processing/contrastive/prepare_data_deepmatcher.py*
Any suggestions? 

Thank you. 

```python
[INFO|trainer.py:1650] 2023-02-06 21:08:47,560 >> ***** Running training *****
[INFO|trainer.py:1651] 2023-02-06 21:08:47,560 >>   Num examples = 1725
[INFO|trainer.py:1652] 2023-02-06 21:08:47,560 >>   Num Epochs = 5
[INFO|trainer.py:1653] 2023-02-06 21:08:47,560 >>   Instantaneous batch size per device = 1024
[INFO|trainer.py:1654] 2023-02-06 21:08:47,560 >>   Total train batch size (w. parallel, distributed & accumulation) = 1024
[INFO|trainer.py:1655] 2023-02-06 21:08:47,560 >>   Gradient Accumulation steps = 1
[INFO|trainer.py:1656] 2023-02-06 21:08:47,560 >>   Total optimization steps = 10
[INFO|trainer.py:1657] 2023-02-06 21:08:47,560 >>   Number of trainable parameters = 124647168
Traceback (most recent call last):
  File "run_pretraining_deepmatcher.py", line 245, in <module>
    main()
  File "run_pretraining_deepmatcher.py", line 231, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/anaconda/envs/azureml_py38_PT_TF/lib/python3.8/site-packages/transformers/trainer.py", line 1543, in train
    return inner_training_loop(
  File "/anaconda/envs/azureml_py38_PT_TF/lib/python3.8/site-packages/transformers/trainer.py", line 1765, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/anaconda/envs/azureml_py38_PT_TF/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/anaconda/envs/azureml_py38_PT_TF/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/anaconda/envs/azureml_py38_PT_TF/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/anaconda/envs/azureml_py38_PT_TF/lib/python3.8/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/anaconda/envs/azureml_py38_PT_TF/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/anaconda/envs/azureml_py38_PT_TF/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "/anaconda/envs/azureml_py38_PT_TF/lib/python3.8/site-packages/transformers/trainer_utils.py", line 700, in __call__
    return self.data_collator(features)
  File "contrastive-product-matching/src/contrastive/data/data_collators.py", line 87, in __call__
    batch_left = self.tokenizer(features_left, padding=True, truncation=True, max_length=self.max_length, return_tensors=self.return_tensors)
  File "/anaconda/envs/azureml_py38_PT_TF/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2523, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "/anaconda/envs/azureml_py38_PT_TF/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2609, in _call_one
    return self.batch_encode_plus(
  File "/anaconda/envs/azureml_py38_PT_TF/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2800, in batch_encode_plus
    return self._batch_encode_plus(
  File "/anaconda/envs/azureml_py38_PT_TF/lib/python3.8/site-packages/transformers/models/roberta/tokenization_roberta_fast.py", line 263, in _batch_encode_plus
    return super()._batch_encode_plus(*args, **kwargs)
  File "/anaconda/envs/azureml_py38_PT_TF/lib/python3.8/site-packages/transformers/tokenization_utils_fast.py", line 429, in _batch_encode_plus
    encodings = self._tokenizer.encode_batch(
TypeError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]
```

**Comment by rpeeters85** [comment]
Hi,

I just tried running the repo from scratch following the instructions in the README and for me your command runs without problems and I cannot reproduce the error. Could you check if the src/processing/preprocess/preprocess_deepmatcher_datasets.py and src/processing/contrastive/prepare_data_deepmatcher.py throw any errors or warnings?

What is your transformers version? I tried it with the one in the .yml file as well with the newest 4.26 and both work without problems.

**Comment by junwei-h** [comment]
Thanks very much for the feedback. It could be due to my local settings. I am using transformers==4.26.0. 

It turns out my error was caused by this [line](https://github.com/makcedward/nlpaug/blob/master/nlpaug/augmenter/word/random.py#L47):

where 
```python
doc = Doc(data, self.tokenizer(data))
```
self.tokenizer on data such as 
`"[COL] brand [VAL] [COL] title [VAL] tomtom gps mount and usb car charger 9s00006 [COL] price [VAL] 28.0 [COL] description [VAL] tomtom..."`

will not treat [COL] as a stopword. Instead, it will tokenize `[COL]` to `[`,`COL`, and `]`. So I have to change `[COL]` to `COL` in [dataset.py](https://github.com/wbsg-uni-mannheim/contrastive-product-matching/blob/main/src/contrastive/data/datasets.py).

In addition, this [line](https://github.com/wbsg-uni-mannheim/contrastive-product-matching/blob/main/src/contrastive/data/datasets.py#L102), where
```python
aug.augment(string)
```
returns a list or a string by chance and I have to change it to 
```python
aux = aug.augment(string)
return aux[0] if type(aux) is list else aux 
```
to ensure a string is returned. 

The above changes solved my problem. Let me know if there is any concern for this change. Thanks.

**Comment by rpeeters85** [comment]
[COL] and [VAL] tokens should actually not be split apart as we add them specifically to the vocabulary of the Transformer (see [Line 109](https://github.com/wbsg-uni-mannheim/contrastive-product-matching/blob/bfcf91f2f9b2b6be8501f321efd930d57ed9f891/src/contrastive/data/datasets.py#L109) in datasets.py). If you are using a custom tokenizer, make sure you do include those as well.

Regarding the augment function: If the input is a string, it should return a string and not a list. Can you double-check that the input you pass to ```aug.augment()``` is really a string and not already a list for some reason?

**Comment by junwei-h** [comment]
Yes, you set it in Line 109, but didn't pass it to `Augmenter` at [Line 114](https://github.com/wbsg-uni-mannheim/contrastive-product-matching/blob/bfcf91f2f9b2b6be8501f321efd930d57ed9f891/src/contrastive/data/datasets.py#L114), 

The 2nd issue may be reproduced by 
```python
import nlpaug.augmenter.word as naw
import nlpaug.augmenter.char as nac

import numpy as np
np.random.seed(42)
import random
random.seed(42)

stopwords = ['[COL]', '[VAL]', 'title', 'name', 'description', 'manufacturer', 'brand', 'specTableContent']
aug_swap = naw.RandomWordAug(action="swap", stopwords=stopwords, aug_p=0.1)

string = "[COL] brand [VAL] [COL] title [VAL] tomtom gps mount and usb car charger 9s00006 [COL] price [VAL] 28.0"
print(aug_swap.augment(string))
#my result shows a list and bracket was tokenized
#['COL [] brand [VAL] [COL] title VAL [tomtom] gps mount and usb car 9s00006 charger [COL] price [VAL] 28. 0']
```

**Comment by rpeeters85** [comment]
As long as the tokenizer knows [COL] and [VAL] as special tokens during initialization it should not split them as in your previous example. Of course it can happen that the augmentation may corrupt them but this should only be the case for the "crop" augmentation as this does not handle pre-defined stopwords (see below).

As far as I understand the documentation of nlpaug your example should not happen as you explicitly pass [COL] and [VAL] as stopwords which should exempt them from augmentation for the swapping operation (see [here](https://nlpaug.readthedocs.io/en/latest/augmenter/word/random.html))

**Comment by junwei-h** [comment]
I was testing action="swap", not crop using the latest version of nlpaug. Have you run the code snippet above and got fine result?

**Comment by Syno8** [comment]
@junwei-h hi, do you reproduce the results in any datasets?

**Comment by rpeeters85** [comment]
i tried running your snippet (copy/paste) and my output is
```COL [] brand [VAL] [COL] title VAL [tomtom] gps mount and usb car 9s00006 charger [COL] price [VAL] 28. 0```

It is not a list, just a simple string as it should be. But the problem of still tokenizing the COL and VAL brackets happens as well for me. So it may be that brackets are not correctly handled by nlpaug when they are part of the stopwords. One would have to look into their source code to see how this is done. Regarding the experiments in this paper I do not think this bug has a large impact on the actual results, I would guess they could minimally improve if this bug was fixed and the tokens were properly excluded from the augmentation.

Thank you for bringing this to my attention!

**Comment by junwei-h** [comment]
Thanks for confirming your run is similar. The impact on your experiment results could be low, but unknown. For Abt-Buy dataset, using R-SupConf(F)+aug is 93.43% (not 94.29% claimed on paper). My batch size has to be reduced to 512 from 1024 to fit the memory; all other hyperparameters are from your paper. 

Would be nice to refresh your experiment results with the bug fixed.
